# Generated by Django 2.1.3 on 2018-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181122_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='available_founds',
            field=models.FloatField(default=0.0),
        ),
    ]
