# Generated by Django 2.1.3 on 2018-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
